kind: pipeline
name: default

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - |
      docker build \
        -t test-image \
        -f build/package/Dockerfile \
        .

steps:
- name: test
  image: golang
  commands:
  - export GO111MODULE=on
  - go test ./...


volumes:
- name: dockersock
  temp: {}


services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

