kind: pipeline
name: build-and-test

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  # wait for the docker service to spin up
  - sleep 5
  # build the image
  - |
      docker build \
        -t test-image \
        -f build/package/Dockerfile \
        .

- name: test
  image: golang
  commands:
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - go test ./...


volumes:
- name: dockersock
  temp: {}


services:
- name: docker
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run

