kind: pipeline
name: testing

steps:
- name: unittests
  image: golang
  commands:
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - go test ./...

- name: lint
  image: golang
  commands:
  # enable go modules
  - export GO111MODULE=on
  - go get -u golang.org/x/lint/golint
  # run tests
  - golint -set_exit_status ./...
