kind: pipeline
name: testing

steps:
- name: unittests
  image: golang
  commands:
  # enable go modules
  - export GO111MODULE=on
  - mkdir -p report
  # run tests
  - go test -covermode=count -coverprofile=report/cover.out ./...

- name: coverage
  image: plugins/codecov
  depends_on:
  - unittests 
  settings:
    token:
      from_secret: CODECOV_TOKEN
    paths:
    - report/
    files:
    - "*.out"

- name: lint
  image: golang
  commands:
  - go get -u golang.org/x/lint/golint
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - golint -set_exit_status ./...

- name: staticcheck
  image: golang
  depends_on:
  - lint
  commands:
  - go get -u honnef.co/go/tools/cmd/staticcheck
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - staticcheck ./...

- name: sonarqube
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

