# core settings for the proxy server
core:
    # log_level of the server
    #
    # This key can be set to:
    #   - "debug"
    #   - "info"
    #
    # If another value is set, chaos-proxy will fall
    # back to the info level.
    log_level: "info"

    # log_format specifies the format to log
    #
    # This key can be set to:
    #   - "text"
    #   - "json"
    #
    # If another value is set, the server will fall back
    # to the text format.
    log_format: "json"

    # address The address chaos-proxy will bind on
    address: "0.0.0.0"

    # port The port chaos-proxy's api will bind on
    port: 3000

# conn configures the connection parameters like bandwidth
# properties and the target for the proxy.
conn:
    testconnection:
        # protocol specifies which protocol should be used for
        # the listener. Valid values are:
        #
        # - 'tcp'
        # - 'udp'
        protocol: "tcp"

        # target specifies the target that should be reached
        # by proxying the requests.
        target: "127.0.0.1:80"

        # bandwidth sets the bandwidth in bit/sec.
        #
        # The default value is set to 8 Mbit/sec. If set to 0 or
        # a negative value, the bandwidth will be unlimited.
        bandwidth: 8388608

        # overhead specifies the header overhead for the packages.
        overhead: "v4_tcp_max"

        # latency configures the minimal and maximal latency in ms.
        latency:
            min: 10
            max: 100

        # loss_rate sets the packet loss rate as a float. Set to 1.0 will
        # drop all packages.
        loss_rate: 0.1

        # listen_port specifies the port to listen on for forwarding packets
        # to the defined target with the configured loss options.
        listen_port: 8080
